version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: backend-container
    ports:
      - "8080:8080"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    depends_on:
      - database
    command: >
      sh -c "
      until nc -z ${DATABASE_HOST} ${DATABASE_PORT}; do
        echo 'Waiting for database to be ready...';
        sleep 2;
      done;
      ./main"

  database:
    image: postgres:14
    container_name: postgres-container
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_URL_DOMAIN: ${URL_DOMAIN}
    container_name: frontend-container
    ports:
      - "3000:80"
    environment:
      - REACT_APP_URL_DOMAIN=${URL_DOMAIN}
    depends_on:
      - backend

volumes:
  postgres-data: